### ISSUE TITLE
[EPIC - ENUMs in DRK IM] Find controlled vocabularies for representing ENUMs

### ISSUE THREAD

**Issue by rohitadeshmukh13** [Fraunhofer-FIT-DSAI/drk-information-model#5]
### Description
- **Goal**: For representing "ENUMs" in semantic metadata models, it would be **preferable use URIs from existing (controlled) vocabularies**
- **Sub-issues**: All the related sub-issues concerning controlled vocabularies for representing ENUMs should be linked to this EPIC issue
- **Creating a new vocabulary**: In case there are no existing vocabularies for a given ENUM, we would need to define the concerned terms under the DRK IM namespace. The first step is listing the terms that the ENUM should contain and a short description in the sub-issues.
- **Issue resolution**: The identified vocabularies can be added eventually to the DRK IM documentation. Until then, the RESULTS section below can be used for reference.

### Example
```ttl
@prefix ex: <http://example.org/> .
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix loclang: <http://id.loc.gov/vocabulary/iso639-2/> .
@prefix gndgeo: <https://d-nb.info/standards/vocab/gnd/geographic-area-code#> .

ex:Movie1 a ex:Movie ;
    dcterms:title "Movie1: subtitle1"@en ;
    ###
    # Languages:
    # Library of Congress's controlled vocabulary for languages based on ISO 639-2: https://id.loc.gov/vocabulary/iso639-2.html 
    # RDF N-Triples representation: https://id.loc.gov/vocabulary/iso639-2.nt
    ###
    ex:language loclang:eng ;
    ###
    # Countries (Geographic Areas):
    # GND Geographic Area Codes: https://d-nb.info/standards/vocab/gnd/geographic-area-code.html
    # RDF TTL representation: https://d-nb.info/standards/vocab/gnd/geographic-area-code.ttl
    ###
    ex:releasedIn gndgeo:XA-DE .
```

### RESULTS: Identified controlled vocabularies
**Domain-agnostic:**
- [ ] Languages
- [ ] Countries

**Culture domain-specific: UC3**
- [ ] Genre (Related to subject: CreativeWork - Play)
- [ ] ProductionType (Related to subject: CreativeWork - Play)
- [ ] AccessModeSufficient (Related to subject: CreativeWork - Play)
- [ ] AccessibilityHazard (Related to subject: CreativeWork - Play)
